<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.tesobe</groupId>
  <artifactId>obp-api-http4s</artifactId>
  <version>1.0-SNAPSHOT</version>
  <name>Archetype - obp-api-http4s</name>
  <url>http://maven.apache.org</url>

  <properties>
    <scala.version>2.12</scala.version>
    <scala.compiler>2.12.19</scala.compiler>
    <lift.version>3.5.0</lift.version>
    <http4s.version>0.23.30</http4s.version>
    <!-- Common plugin settings -->
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>${project.build.sourceEncoding}</project.reporting.outputEncoding>
    <!-- vscaladoc settings -->
    <maven.scaladoc.vscaladocVersion>1.2-m1</maven.scaladoc.vscaladocVersion>

    <!--java version, can be: [8,9,10,11,12,13]-->
    <java.version>11</java.version>
    <maven.compiler.source>${java.version}</maven.compiler.source>
    <maven.compiler.target>${java.version}</maven.compiler.target>
  </properties>


  <dependencies>
<!--    <dependency>-->
<!--      <groupId>com.tesobe</groupId>-->
<!--      <artifactId>obp-commons</artifactId>-->
<!--    </dependency>-->
<!--    <dependency>-->
<!--      <groupId>com.example</groupId>-->
<!--      <artifactId>obp-commons</artifactId>-->
<!--      <version>1.10.1</version>-->
<!--      <scope>system</scope>-->
<!--      <systemPath>${project.basedir}/libs/obp-commons-1.10.1.jar</systemPath>-->
<!--    </dependency>-->
<!--    <dependency>-->
<!--      <groupId>com.example</groupId>-->
<!--      <artifactId>obp-api</artifactId>-->
<!--      <version>1.10.1</version>-->
<!--      <scope>system</scope>-->
<!--      <systemPath>${project.basedir}/libs/obp-api.jar</systemPath>-->
<!--    </dependency>-->
    <dependency>
      <groupId>org.http4s</groupId>
      <artifactId>http4s-ember-server_${scala.version}</artifactId>
      <version>${http4s.version}</version>
    </dependency>
    <dependency>
      <groupId>org.http4s</groupId>
      <artifactId>http4s-dsl_${scala.version}</artifactId>
      <version>${http4s.version}</version>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <version>1.2.13</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-assembly-plugin</artifactId>
      <version>3.7.1</version>
      <configuration>
        <archive>
          <manifest>
            <mainClass>http4s.Http4sServer</mainClass>
          </manifest>
        </archive>
      </configuration>
      <executions>
        <execution>
          <phase>package</phase>
          <goals>
            <goal>single</goal>
          </goals>
        </execution>
      </executions>
      </plugin>
      <plugin>
        <groupId>net.alchim31.maven</groupId>
        <artifactId>scala-maven-plugin</artifactId>
        <version>4.8.1</version>
        <configuration>
          <scalaVersion>${scala.compiler}</scalaVersion>
          <displayCmd>true</displayCmd>
          <jvmArgs>
            <jvmArg>-DpackageLinkDefs=file://${project.build.directory}/packageLinkDefs.properties</jvmArg>
            <jvmArg>-Xms64m</jvmArg>
            <jvmArg>-Xmx1024m</jvmArg>
          </jvmArgs>
          <args>
            <arg>-unchecked</arg>
            <arg>-explaintypes</arg>
            <arg>-Ypartial-unification</arg>
          </args>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
              <goal>testCompile</goal>
            </goals>
          </execution>
          <execution>
            <id>scala-test-compile</id>
            <phase>process-test-resources</phase>
            <goals>
              <goal>testCompile</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.13.0</version>
        <configuration>
          <release>${java.version}</release>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
